// src/format.mjs
//
// Formats the structured review JSON into the final GitHub Markdown output.

export const COMMENT_MARKER = "<!-- smart-reviewer-walkthrough -->";

export function sanitizeMermaid(code) {
  if (!code) return "";
  return code
    .split("\n")
    .map((line) => {
      return line.replace(
        /(\b[A-Za-z0-9_]+)(\[|\{)([^\n"\]\}]+)(\]|\})/g,
        (match, id, open, text, close) => {
          if (text.startsWith('"') && text.endsWith('"')) return match;
          if (/[\(\):?=<>&]/.test(text)) {
            const safeText = text.replace(/"/g, "'");
            return `${id}${open}"${safeText}"${close}`;
          }
          return match;
        }
      );
    })
    .join("\n");
}

export function formatComment({ walkthrough, model, riskEvaluation, teamMemory, truncated, omittedFiles }) {
  const {
    repo_context: repoContext,
    summary,
    mermaid_diagram: mermaid,
    blocking = [],
    should_fix: shouldFix = [],
    nice_to_have: niceToHave = [],
    verified = [],
    suggested_rules: suggestedRules = [],
  } = walkthrough;

  const lines = [
    COMMENT_MARKER,
    "## 🧭 Smart Reviewer Walkthrough",
    "",
  ];

  // 1. Repository Architectural Context
  if (repoContext) {
    lines.push(
      "### 🏛️ Repository & Architectural Context",
      `* **Architectural Role:** ${repoContext.architectural_role}`,
      `* **Operational & Risk Lens:** ${repoContext.em_strategic_lens}`,
      "",
      "---",
      ""
    );
  }

  // 2. Risk Gate Verdict
  if (riskEvaluation) {
    const icon = riskEvaluation.riskLevel === "HIGH" ? "🔴" : (riskEvaluation.riskLevel === "MEDIUM" ? "🟡" : "🟢");
    lines.push(
      `### 🚦 Risk Gate: ${icon} ${riskEvaluation.riskLevel} RISK (${riskEvaluation.recommendation})`,
      `* **Diff Metrics:** ${riskEvaluation.totalLinesChanged} lines changed across ${riskEvaluation.fileCount} file(s)`,
      riskEvaluation.reasons?.length ? `* **Gate Triggers:** ${riskEvaluation.reasons.join(" • ")}` : "",
      riskEvaluation.recommendedReviewers?.length
        ? `* **Recommended Reviewers (${riskEvaluation.reviewerSource}):** ${riskEvaluation.recommendedReviewers.join(" ")}`
        : "",
      "",
      "---",
      ""
    );
  }

  // 3. Summary
  lines.push(
    "### 📝 Summary",
    summary,
    ""
  );

  // 4. Mermaid Flowchart (Collapsible for neatness)
  if (mermaid && mermaid.trim()) {
    const cleanMermaid = sanitizeMermaid(mermaid);
    lines.push(
      "<details open>",
      "<summary><b>🗺️ Data Flow Diagram</b></summary>",
      "",
      "```mermaid",
      cleanMermaid.trim(),
      "```",
      "",
      "</details>",
      ""
    );
  }

  // 5. Findings: Blocking, Should Fix, Nice to Have, Verified
  lines.push(...formatFindingsSection("🚫 Blocking (Do Not Merge Until Resolved)", blocking));
  lines.push(...formatFindingsSection("⚠️ Should Fix (Address Before Release)", shouldFix));
  lines.push(...formatListSection("💡 Nice to Have (Optional Polish)", niceToHave));
  lines.push(...formatListSection("✅ Verified (Safe — Skip Manual Re-Checking)", verified));

  // 6. Compounding Loop: Suggested Rules for AGENTS.md
  if (suggestedRules.length > 0) {
    lines.push(
      "<details>",
      "<summary><b>📝 Suggested Rule Additions for Team Memory (Needs Human Approval)</b></summary>",
      "",
      "The reviewer noticed conventions or failure patterns in this PR. Consider committing these to your rules file:",
      ""
    );
    for (const { rules_file, bullet } of suggestedRules) {
      lines.push(`- **\`${rules_file}\`**: ${bullet}`);
    }
    lines.push("", "</details>", "");
  }

  // 7. Context transparency footer
  if (teamMemory?.filesLoaded?.length) {
    lines.push(`<sub>📚 Evaluated against Team Memory: ${teamMemory.filesLoaded.map((f) => `\`${f}\``).join(", ")}</sub>`, "");
  }

  if (truncated) {
    lines.push(
      `> ⚠️ This diff was large — ${omittedFiles.length} file(s) were not analyzed: ${omittedFiles.slice(0, 10).join(", ")}${omittedFiles.length > 10 ? ", …" : ""}.`,
      ""
    );
  }

  lines.push(`<sub>Generated by Smart Reviewer Walkthrough using \`${model}\`. AI-generated — verify before relying on it.</sub>`);

  return lines.filter((l) => l !== undefined).join("\n");
}

function formatFindingsSection(title, items) {
  if (!items || items.length === 0) {
    return [`### ${title}`, "", "None found.", ""];
  }
  const lines = [`### ${title}`, ""];
  for (const item of items) {
    if (typeof item === "string") {
      lines.push(`- ${item}`);
    } else {
      lines.push(`- **\`${item.file}:${item.line}\`** — ${item.issue}`);
    }
  }
  lines.push("");
  return lines;
}

function formatListSection(title, items) {
  if (!items || items.length === 0) {
    return [`### ${title}`, "", "None noted.", ""];
  }
  const lines = [`### ${title}`, ""];
  for (const item of items) {
    lines.push(`- ${item}`);
  }
  lines.push("");
  return lines;
}
