export const COMMENT_MARKER = "<!-- smart-reviewer-walkthrough -->";

const RISK_LABEL = {
  race_condition: "Race condition",
  null_undefined: "Null/undefined risk",
  unhandled_error: "Unhandled error",
  resource_leak: "Resource leak",
  other: "Risk",
};

export function formatComment({ walkthrough, model, truncated, omittedFiles }) {
  const { summary, mermaid_diagram: mermaid, focus_points: focusPoints } = walkthrough;

  const lines = [
    COMMENT_MARKER,
    "## 🔎 Smart Reviewer Walkthrough",
    "",
    summary,
    "",
    "```mermaid",
    mermaid.trim(),
    "```",
    "",
  ];

  if (focusPoints.length > 0) {
    lines.push("### 👀 Focus Your Eyes Here");
    focusPoints.forEach((point, i) => {
      const label = RISK_LABEL[point.risk_type] || RISK_LABEL.other;
      lines.push(`${i + 1}. **\`${point.file}:${point.line}\`** — ${label}: ${point.reason}`);
    });
    lines.push("");
  } else {
    lines.push("### 👀 Focus Your Eyes Here", "", "No specific race-condition, null, or error-handling risks stood out in this diff.", "");
  }

  if (truncated) {
    lines.push(
      `> ⚠️ This diff was large — ${omittedFiles.length} file(s) were not analyzed: ${omittedFiles.slice(0, 10).join(", ")}${omittedFiles.length > 10 ? ", …" : ""}.`,
      ""
    );
  }

  lines.push(`<sub>Generated by Smart Reviewer Walkthrough using \`${model}\`. AI-generated — verify before relying on it.</sub>`);

  return lines.join("\n");
}
